site_name: Knowledge Base
theme:
  name: 'material'
  palette:
    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    # Toggle dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  font:
    text: 'Roboto'
    code: 'Fira Mono'
  language: en
  logo: 'images/favicon.png'
  favicon:
    'images/favicon.png'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

repo_name: 'SheepCommander.github.io'
repo_url: 'https://github.com/SheeepCommander/SheepCommander.github.io'

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search:
      lang: en

copyright: This unofficial site is not associated/approved by Mojang.