# Project information
site_name: Knowledge Base
site_url: https://sheepcommander.github.io/
site_author: SheepCommander, Anthonietta, KodingKat & MMK21
site_description: Find resources for MineCraft commands, datapacks, & resource packs

# Repository, turned of edit
repo_name: SheepCommander/SheepCommander.github.io
repo_url: https://github.com/SheepCommander/SheepCommander.github.io
edit_uri: ""

# Copyright
copyright: This unofficial site is not associated/approved by Mojang.

# Configuration
theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  palette:
    # Slate = Dark mode; Default = Light mode
    scheme: slate
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en

  favicon: assets/favicon.png
  logo: assets/favicon.png

  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.instant
    # Autohide header when user scrolls past a certain threshold
    - header.autohide

  # Would Change the icon displayed for the git repo
#  icon:
#    repo: fontawesome/brands/git-alt

# Plugins
plugins:
  # Search bar
  - search
    lang: en

# Extra
extra:
  # Generates icons at footer next to copyright
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk