# Project information
site_name: Knowledge Base
site_url: https://squidfunk.github.io/mkdocs-material/
site_author: SheepCommander, Anthonietta, KodingKat & MMK21
site_description: Find resources for MineCraft commands, datapacks, & resource packs

# Repository
repo_name: SheepCommander/SheepCommander.github.io
repo_url: https://github.com/SheepCommander/SheepCommander.github.io
edit_uri: ""

# Copyright
copyright: This unofficial site is not associated/approved by Mojang.

# Configuration
theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo


markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search:
      lang: en